version: "2"

services:
  web:
    build: web
    ports:
    - 80
  db:
    build: db
    environment:
      POSTGRES_PASSWORD: verysecretpassword
  words:
    build: words
    environment:
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: verysecretpassword
